// <auto-generated />
using System;
using Drinkful.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Drinkful.Infrastructure.Migrations
{
    [DbContext(typeof(DrinkfulDbContext))]
    [Migration("20230115201815_InitialDrinkData")]
    partial class InitialDrinkData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Drinkful.Domain.Drink.Drink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Drinks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00b29fa1-38b7-4718-aef3-58390f6653d3"),
                            AuthorId = new Guid("77a64a67-1cb1-4bb4-b415-df41e1bd42de"),
                            CreatedAt = new DateTime(2023, 1, 15, 20, 18, 15, 56, DateTimeKind.Utc).AddTicks(4758),
                            Description = "A cappuccino is an espresso-based coffee drink that originated in Austria and was later popularized in Italy and is prepared with steamed milk foam. Variations of the drink involve the use of cream instead of milk, using non-dairy milk substitutes and flavoring with cinnamon or chocolate powder.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Cappuccino_at_Sightglass_Coffee.jpg/1024px-Cappuccino_at_Sightglass_Coffee.jpg",
                            Name = "Cappuccino",
                            Summary = "Coffee drink",
                            UpdatedAt = new DateTime(2023, 1, 15, 20, 18, 15, 56, DateTimeKind.Utc).AddTicks(4761)
                        },
                        new
                        {
                            Id = new Guid("fc3eb9a0-c574-46f0-b715-93b6df8be3fb"),
                            AuthorId = new Guid("1ed1ad02-0caa-470c-942c-462ffb41ecdc"),
                            CreatedAt = new DateTime(2023, 1, 15, 20, 18, 15, 56, DateTimeKind.Utc).AddTicks(4783),
                            Description = "A Moscow mule is a cocktail made with vodka, ginger beer and lime juice, garnished with a slice or wedge of lime and a sprig of mint. The drink is a type of buck and is sometimes called a vodka buck. The Moscow mule is popularly served in a copper mug, which takes on the cold temperature of the liquid.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/8/89/Cocktail_Moscow_Mule_im_Kupferbecher_mit_Minze.jpg",
                            Name = "Moscow mule",
                            Summary = "Cocktail",
                            UpdatedAt = new DateTime(2023, 1, 15, 20, 18, 15, 56, DateTimeKind.Utc).AddTicks(4784)
                        });
                });

            modelBuilder.Entity("Drinkful.Domain.Drink.Drink", b =>
                {
                    b.OwnsMany("Drinkful.Domain.Drink.Entities.DrinkComment", "Comments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("CommentId");

                            b1.Property<Guid>("DrinkId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("AuthorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id", "DrinkId");

                            b1.HasIndex("DrinkId");

                            b1.ToTable("DrinkComments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DrinkId");
                        });

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
